### ISSUE TITLE
Custom Payment

### ISSUE THREAD

**Issue by kolawoletech** [Marketcloud/node-marketcloud-starter#1]
I need to add a custom payment, how do I go about that?

**Comment by fatmatto** [comment]
Hey @kolawoletech  to add a custom payment you need to go to your store's dashboard and the click on system > payments. In this view, in the top right corner you have "add payment method" and here you can create a new payment method.

This payment method can then be used when creating an order by passing the "payment_method_id" property to the new order.

**Comment by kolawoletech** [comment]
I did, I still get the same error msg

this.marketcloud.client.payments.create({
            method : 'PayFast', 
            order_id : response.data.id,
            payment_method_id: 'PayFast'            
          })

**Comment by fatmatto** [comment]
Hey can you try to update the sdk version in your project?

**Comment by kolawoletech** [comment]
code: 401, type: "Unauthorized", message: "Client is not authorized to perform this action, i…ic" but a higher authorization level is required."}

I did but I get the above error

**Comment by fatmatto** [comment]
Hey @kolawoletech  it was an issue with api permission on the payments endpoint, now you should not get the 401 response

**Comment by kolawoletech** [comment]
Thanks for fixing, it works now
